### PR TITLE
Convert AudioLink panel icons & shader to use MSDF format

### PR DESCRIPTION
**Pull request by JLChnToZ**
This is the changes according to #306.
If any more icons that need to migrate, I will include in here as well.

### CODE REVIEW

**Comment by float3** [comment]
looks good to me, can you add the source files as well?

**Comment by JLChnToZ** [comment]
Yes I can, but IDK where to put it.

**Comment by pema99** [comment]
Put them somewhere in the asset folder of AudioLinkSandboxProject. Doesn't really matter where

**Review by pema99 — APPROVED** [review]

**Comment by pema99** [comment]
Thanks 👍

**Pull request merged**
