### PR TITLE
Try and Catch on Unlink

### PR DESCRIPTION
**Pull request by fundale**
Attempts to recover from a invalid `UnlinkAnalyser()` call

### CODE REVIEW

**Comment by float3** [comment]
do you wanna tackle color chord in the same PR?

**Comment by fundale** [comment]
> do you wanna tackle color chord in the same PR?

Looked into it,
ColorChord appears to be functioning, but under the threshold for the panel display,
the entire CC strip and notes are sparse, however I'm not familiar with how CC works internally.
cnlohr added it correct? maybe they have an idea on where to check?

**Comment by float3** [comment]
if it's functioning what's the problem?

**Comment by fundale** [comment]
Ok so, it's functioning in that it is returning a value, but not functioning in that it's return value is close to 0

**Comment by float3** [comment]
oh interesting

**Pull request merged**
